### ISSUE TITLE
Permit syntactic oddities?

### ISSUE THREAD

**Issue by mlhetland** [tkluck/HAML.jl#6]
I may be missing some mechanism in the current library, but while trying to recreate some existing HTML5, I ran into the following roadblocks (for non-XML HTML5 syntax oddities):

- Equals-signs in attribute values are auto-escaped, which means I can't generate, e.g., `content="width=device-width, initial-scale=1"`.
- Attributes must have values, which means I can't generate, e.g., `<script defer …>`.
- Tags are always closed (either empty or with a closing tag), which means I can't generate, e.g., `<meta charset="utf-8">`.

Now, it may be that the more XML-friendly `'width&#61;device-width …'`, `defer=""` and `<meta …/>` are just fine HTML5-wise – so permitting stuff light this might just add unnecessary complication? ¯\_(ツ)_/¯

(BTW, for the value-less attributes, I tested using `defer=nothing` – a solution I've used myself in similar situations, but that seems to have broken the rendering completely, including for the following attributes.)

**Comment by tkluck** [comment]
This all makes sense! I created #7 #8 #9 to track the individual issues you raise. I'll close this one to keep it organised.

**Comment by mlhetland** [comment]
Thanks! (I debated creating multiple issues, but decided against it, since I was unsure about the merit of it all.)
